version: '3.4'

services:
  back-api:
    container_name: back-api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: AutoSupportAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      
  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - ./Data/seed_postgres_test.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_USER=pgtest
      - POSTGRES_DB=pgtest
      - POSTGRES_PASSWORD=pgtest

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./Data/seed_redis_test.txt:/tmp/seed.txt
    #volumes:
      #- ./Data/Redis:/Redis
    #entrypoint: sh -c /Redis/seed_redis.sh
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
