// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20231228140246_SeedMoreTestData")]
    partial class SeedMoreTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.AnswerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Answer = "No, FU"
                        },
                        new
                        {
                            Id = 2L,
                            Answer = "MaybeMaybe"
                        },
                        new
                        {
                            Id = 3L,
                            Answer = "MoreAnswers"
                        },
                        new
                        {
                            Id = 4L,
                            Answer = "MoreAnswers 2"
                        });
                });

            modelBuilder.Entity("Database.Entities.QuestionAnswerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnswerId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionAnswerEntity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AnswerId = 1L,
                            QuestionId = 1L,
                            Rank = 2
                        },
                        new
                        {
                            Id = 2L,
                            AnswerId = 2L,
                            QuestionId = 1L,
                            Rank = 1
                        },
                        new
                        {
                            Id = 3L,
                            AnswerId = 2L,
                            QuestionId = 2L,
                            Rank = 2
                        },
                        new
                        {
                            Id = 4L,
                            AnswerId = 4L,
                            QuestionId = 2L,
                            Rank = 1
                        });
                });

            modelBuilder.Entity("Database.Entities.QuestionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Question = "Did it work?"
                        },
                        new
                        {
                            Id = 2L,
                            Question = "Will I finish in time?"
                        });
                });

            modelBuilder.Entity("Database.Entities.QuestionAnswerEntity", b =>
                {
                    b.HasOne("Database.Entities.AnswerEntity", "Answer")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.QuestionEntity", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Database.Entities.AnswerEntity", b =>
                {
                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Database.Entities.QuestionEntity", b =>
                {
                    b.Navigation("QuestionAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
